### PR TITLE
Add clean/dirty optimization

### PR DESCRIPTION
**Pull request by YehorBoiar**
This PR's aim is to implement clean/dirty optimization for our reduce function.

Approach:

I would create a new struct called Skelet. 
**Pseudocode**
```rust
struct Skeleton<'a> {
    clean_map: HashMap<&'a Tree_Node, bool>,
}
impl<`a> Skeleton<`a> {
fn set_clean()
}
```

Replace uniplate subtree with our Skeleton strucure, implement clean dirty using that
```rust
fn reduce_iteration<T, M, F>(
    commands: &mut Commands<T, M>,
    transform: &F,
    subtree: &S,
    meta: &M,
) -> Option<T> // Would we need to return T or S?
where
    S: Skeleton,
    T: Uniplate,
    F: Fn(&mut Commands<T, M>, &T, &M) -> Option<T>,
{
    // Step 1: Check if the current subtree is already clean; if so, return None.
    if subtree.is_clean() {
        return None;
    }

    // Step 2: Attempt to apply the transformation using the provided `transform` function.
    match transform(commands, subtree, meta) {
        Some(new_tree) => {
            // If the transformation succeeds, return the new transformed subtree.
            return Some(new_tree);
        }
        None => {
            // If the transformation returns `None`, clear any side effects in `commands`.
            commands.clear(); // This ensures that partial changes are not retained.
        }
    }

    // Step 3: Attempt to recursively apply the transformation to each child.
    let mut children = subtree.children();
    for i in 0..children.len() {
        // Recursively call `reduce_iteration` on each child.
        if let Some(new_child) = reduce_iteration(commands, transform, &children[i], meta) {
            // If a child was updated, replace it in the children array.
            children[i] = new_child;

            // Return a new subtree with updated children.
            return Some(subtree.with_children(children));
        }
    }

    // Step 4: Ensure that all children are marked as clean.
    assert!(subtree.children().iter().all(|c| c.is_clean()));

    // Step 5: Mark the subtree as clean to indicate it no longer needs processing.
    subtree.set_clean(true);

    // Return None, as no further changes are needed.
    None
}
```

### CODE REVIEW

**Comment by YehorBoiar** [comment]
Accidentally deleted branch from my repo

**Comment by YehorBoiar** [comment]
In reduce_iteration, would still like to return Option<T>? @lixitrixi

**Comment by lixitrixi** [comment]
> In reduce_iteration, would still like to return Option? @lixitrixi

It should still return an `Option` since it might not apply any rules. `None` is what we use to signify that no reduction was made. Even with the coming API updates this will still be the case, although it will return a different type inside the `Option`. Is that what you are asking?

**Comment by lixitrixi** [comment]
> `clean_map: HashMap<&'a Tree_Node, bool>,`

I'm not sure a HashMap is the way to go here, as hashing can be quite slow for potentially large data types like the arbitrary-sized trees we're dealing with here. Additionally, identical but separate subtrees in the tree will hash to the same value which means they will share a dirty/clean value. Although this is correct (both trees should be clean since they are identical), the question arises of what if we want to add some other un-shareable metadata to each node in the tree besides a clean/dirty flag?

I believe something may have been lost in my explanation, sorry for the lack of clarity! What I meant was something like the (rough) code below:

```rust
struct Skeleton<'a, T> 
where
    T: Uniplate
{
    clean: bool, // clean/dirty flag
    node: &'a T, // reference to existing node in tree
    children: Vec<Skeleton<T>>, // skeletons which contain references to this skeleton's node's children.
}
```

1. A tree using these would be constructed once at the start, with one Skeleton for every node in the tree. The skeleton tree will be the exact same shape as the input tree, with each Skeleton node holding a reference to the corresponding input tree node.
2. `reduce_iteration` will accept a `Skeleton<T>` rather than simple a `T` as its `subtree`. To get the actual input tree node it uses the skeleton node's reference.
3. When a rule returns a reduction, we need to wrap the resulting subtree in a Skeleton tree in the same way we did at the start. These skeleton nodes will all be dirty as expected.
4. When a recursive call returns a new child node because of a successful reduction, we replace the parent node's child at that index as normal. But we then need to return a `Skeleton` which uses the new child as well.

**Pull request closed without merging**
